# Generated by Django 5.0.2 on 2024-02-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_roles_studentrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='role',
        ),
    ]
