# Generated by Django 5.0.2 on 2024-03-16 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=False, serialize=False,
                                      to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
                'db_table': 'supervisor',
                'ordering': ('user',),
            },
        ),
    ]
