# Generated by Django 5.0.2 on 2024-03-17 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_supervisor_id_alter_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Студент'), ('SUPERVISOR', 'Куратор'), ('ADMINISTRATOR', 'Администратор')], default='STUDENT', max_length=15, verbose_name='Роль пользователя'),
        ),
    ]
