# Generated by Django 5.0.2 on 2024-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_supervisor_id_alter_supervisor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('SUPERVISOR', 'Куратор'), ('ADMINISTRATOR', 'Администратор')], default='STUDENT', max_length=15, verbose_name='Роль пользователя'),
        ),
    ]
