# Generated by Django 5.0.2 on 2024-02-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('SUPERVISOR', 'Куратор')], default='STUDENT', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Студент'), ('SUPERVISOR', 'Куратор')], default='SUPERVISOR', max_length=20, verbose_name='Роль'),
        ),
    ]
