# Generated by Django 5.0.2 on 2024-02-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_project_description'),
        ('Users', '0003_roles_studentrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.roles')),
            ],
        ),
    ]
