# Generated by Django 5.0.2 on 2024-03-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstudent',
            name='participation',
            field=models.BooleanField(default=False),
        ),
    ]
