# Generated by Django 5.0.2 on 2024-03-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_projectrole'),
        ('Users', '0004_remove_student_role_remove_supervisor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.supervisor')),
            ],
        ),
    ]
